name: CI
on: push
jobs:
  CI:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run contains(github.ref, 'release')
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - name: Release
        if: ${{ contains(github.ref, 'master') || contains(github.ref, 'next') }}
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
